<?php

namespace Mix\Database\Coroutine;

use Mix\Core\Coroutine\Coroutine;

/**
 * PDOCoroutine组件
 * @author LIUJIAN <coder.keda@gmail.com>
 */
class PDOConnection extends \Mix\Database\Persistent\PDOConnection
{

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 开启协程
        Coroutine::enable();
    }

}
