<?php

namespace Mix\Database\Pool;

use Mix\Pool\ConnectionPoolInterface;
use Mix\Pool\AbstractConnectionPool;

/**
 * Class ConnectionPool
 * @author LIUJIAN <coder.keda@gmail.com>
 * @package Mix\Database\Pool
 */
class ConnectionPool extends AbstractConnectionPool implements ConnectionPoolInterface
{

    /**
     * 获取连接
     * @return \Mix\Database\Coroutine\PDOConnection
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }

}
