<?php

namespace Mix\Database\Base;

use Mix\Core\Component\AbstractComponent;
use Mix\Database\PDOConnectionInterface;
use Mix\Database\Query\BuildHelper;
use Mix\Database\Query\Expression;
use Mix\Database\QueryBuilder;

/**
 * Class AbstractPDOConnection
 * @package Mix\Database\Base
 * @author liu,jian <coder.keda@gmail.com>
 */
abstract class AbstractPDOConnection extends AbstractComponent implements PDOConnectionInterface
{

    /**
     * 数据源格式
     * @var string
     */
    public $dsn = '';

    /**
     * 数据库用户名
     * @var string
     */
    public $username = 'root';

    /*
     * 数据库密码
     */
    public $password = '';

    /**
     * 驱动连接选项
     * @var array
     */
    public $driverOptions = [];

    /**
     * PDO
     * @var \PDO
     */
    protected $_pdo;

    /**
     * PDOStatement
     * @var \PDOStatement
     */
    protected $_pdoStatement;

    /**
     * sql片段
     * @var array
     */
    protected $_sqlFragments = [];

    /**
     * sql
     * @var string
     */
    protected $_sql = '';

    /**
     * params
     * @var array
     */
    protected $_params = [];

    /**
     * values
     * @var array
     */
    protected $_values = [];

    /**
     * sql原始数据
     * @var array
     */
    protected $_sqlPrepareData = [];

    /**
     * 默认驱动连接选项
     * @var array
     */
    protected $_defaultDriverOptions = [
        \PDO::ATTR_EMULATE_PREPARES   => false,
        \PDO::ATTR_ERRMODE            => \PDO::ERRMODE_EXCEPTION,
        \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
    ];

    /**
     * 驱动连接选项
     * @var array
     */
    protected $_driverOptions = [];

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 设置驱动连接选项
        $this->_driverOptions = $this->driverOptions + $this->_defaultDriverOptions;
    }

    /**
     * 创建连接
     * @return \PDO
     */
    protected function createConnection()
    {
        $pdo = new \PDO(
            $this->dsn,
            $this->username,
            $this->password,
            $this->_driverOptions
        );
        return $pdo;
    }

    /**
     * 关闭连接
     * @return bool
     */
    public function disconnect()
    {
        $this->_pdoStatement = null;
        $this->_pdo          = null;
        return true;
    }

    /**
     * 查询构建
     * @param $item
     * @return $this
     */
    public function queryBuilder($item)
    {
        if (isset($item['if']) && $item['if'] == false) {
            return $this;
        }
        if (isset($item['params'])) {
            $this->bindParams($item['params']);
        }
        $this->_sqlFragments[] = array_shift($item);
        return $this;
    }

    /**
     * 创建命令
     * @param null $sql
     * @return $this
     */
    public function createCommand($sql = null)
    {
        // 清扫数据
        $this->_sql    = '';
        $this->_params = [];
        $this->_values = [];
        // 字符串构建
        if (is_string($sql)) {
            $this->_sql = $sql;
        }
        // 数组构建
        if (is_array($sql)) {
            foreach ($sql as $item) {
                $this->queryBuilder($item);
            }
            $this->_sql = implode(' ', $this->_sqlFragments);
        }
        if (is_null($sql)) {
            $this->_sql = implode(' ', $this->_sqlFragments);
        }
        // 清扫数据
        $this->_sqlFragments = [];
        // 保存SQL
        $this->_sqlPrepareData = [$this->_sql];
        // 返回
        return $this;
    }

    /**
     * 绑定参数
     * @param $data
     * @return $this
     */
    public function bindParams($data)
    {
        $this->_params += $data;
        return $this;
    }

    /**
     * 绑定值
     * @param $data
     * @return $this
     */
    protected function bindValues($data)
    {
        $this->_values += $data;
        return $this;
    }

    /**
     * 返回当前PDO连接是否在事务内（在事务内的连接回池会造成下次开启事务产生错误）
     * @return bool
     */
    public function inTransaction()
    {
        /** @var  $Pdo \PDO */
        $Pdo = $this->_pdo;
        return (bool)($Pdo ? $Pdo->inTransaction() : false);
    }

    /**
     * 返回一个RawQuery对象，对象的值将不经过参数绑定，直接解释为SQL的一部分，适合传递数据库原生函数
     * @param $value
     * @return \Mix\Database\Query\Expression
     */
    public static function raw($value)
    {
        return new Expression($value);
    }

    /**
     * 绑定数组参数
     * @param $sql
     * @param $params
     * @return array
     */
    protected static function bindArrayParams($sql, $params)
    {
        foreach ($params as $key => $item) {
            if (is_array($item)) {
                unset($params[$key]);
                $key = substr($key, 0, 1) == ':' ? $key : ":{$key}";
                $sql = str_replace($key, implode(', ', static::quotes($item)), $sql);
            }
        }
        return [$sql, $params];
    }

    /**
     * 连接
     */
    protected function connect()
    {
        $this->_pdo = $this->createConnection();
    }

    /**
     * 自动连接
     */
    protected function autoConnect()
    {
        if (isset($this->_pdo)) {
            return;
        }
        $this->connect();
    }

    /**
     * 预处理
     */
    protected function prepare()
    {
        // 自动连接
        $this->autoConnect();
        // 准备与参数绑定
        if (!empty($this->_params)) {
            // 原始方法
            foreach ($this->_params as $key => $item) {
                if ($item instanceof Expression) {
                    unset($this->_params[$key]);
                    $key        = substr($key, 0, 1) == ':' ? $key : ":{$key}";
                    $this->_sql = str_replace($key, $item->getValue(), $this->_sql);
                }
            }
            // 有参数
            list($sql, $params) = static::bindArrayParams($this->_sql, $this->_params);
            $this->_pdoStatement   = $this->_pdo->prepare($sql);
            $this->_sqlPrepareData = [$sql, $params, []]; // 必须在 bindParam 前，才能避免类型被转换
            foreach ($params as $key => &$value) {
                $this->_pdoStatement->bindParam($key, $value);
            }
        } elseif (!empty($this->_values)) {
            // 批量插入
            $this->_pdoStatement   = $this->_pdo->prepare($this->_sql);
            $this->_sqlPrepareData = [$this->_sql, [], $this->_values];
            foreach ($this->_values as $key => $value) {
                $this->_pdoStatement->bindValue($key + 1, $value);
            }
        } else {
            // 无参数
            $this->_pdoStatement   = $this->_pdo->prepare($this->_sql);
            $this->_sqlPrepareData = [$this->_sql];
        }
    }

    /**
     * 清扫预处理数据
     */
    protected function clearPrepare()
    {
        $this->_sql    = '';
        $this->_params = [];
        $this->_values = [];
    }

    /**
     * 返回结果集
     * @return \PDOStatement
     */
    public function query()
    {
        $this->prepare();
        $this->_pdoStatement->execute();
        $this->clearPrepare();
        return $this->_pdoStatement;
    }

    /**
     * 返回一行
     * @return mixed
     */
    public function queryOne()
    {
        $this->prepare();
        $this->_pdoStatement->execute();
        $this->clearPrepare();
        return $this->_pdoStatement->fetch($this->_driverOptions[\PDO::ATTR_DEFAULT_FETCH_MODE]);
    }

    /**
     * 返回多行
     * @return array
     */
    public function queryAll()
    {
        $this->prepare();
        $this->_pdoStatement->execute();
        $this->clearPrepare();
        return $this->_pdoStatement->fetchAll();
    }

    /**
     * 返回一列 (第一列)
     * @param int $columnNumber
     * @return array
     */
    public function queryColumn($columnNumber = 0)
    {
        $this->prepare();
        $this->_pdoStatement->execute();
        $this->clearPrepare();
        $column = [];
        while ($row = $this->_pdoStatement->fetchColumn($columnNumber)) {
            $column[] = $row;
        }
        return $column;
    }

    /**
     * 返回一个标量值
     * @return mixed
     */
    public function queryScalar()
    {
        $this->prepare();
        $this->_pdoStatement->execute();
        $this->clearPrepare();
        return $this->_pdoStatement->fetchColumn();
    }

    /**
     * 执行SQL语句
     * @return bool
     */
    public function execute()
    {
        $this->prepare();
        $success = $this->_pdoStatement->execute();
        $this->clearPrepare();
        return $success;
    }

    /**
     * 返回最后插入行的ID或序列值
     * @return string
     */
    public function getLastInsertId()
    {
        return $this->_pdo->lastInsertId();
    }

    /**
     * 返回受上一个 SQL 语句影响的行数
     * @return int
     */
    public function getRowCount()
    {
        return $this->_pdoStatement->rowCount();
    }

    /**
     * 返回原生SQL语句
     * @return string
     */
    public function getRawSql()
    {
        $sqlPrepareData = $this->_sqlPrepareData;
        if (count($sqlPrepareData) > 1) {
            list($sql, $params, $values) = $sqlPrepareData;
            $values = static::quotes($values);
            $params = static::quotes($params);
            // 先处理 values，避免 params 中包含 ? 号污染结果
            $sql = vsprintf(str_replace('?', '%s', $sql), $values);
            // 处理 params
            foreach ($params as $key => $value) {
                $key = substr($key, 0, 1) == ':' ? $key : ":{$key}";
                $sql = str_replace($key, $value, $sql);
            }
            return $sql;
        }
        return array_shift($sqlPrepareData);
    }

    /**
     * 给字符串加单引号
     * @param $var
     * @return array|string
     */
    protected static function quotes($var)
    {
        if (is_array($var)) {
            foreach ($var as $k => $v) {
                $var[$k] = static::quotes($v);
            }
            return $var;
        }
        return is_string($var) ? "'{$var}'" : $var;
    }

    /**
     * 插入
     * @param string $table
     * @param array $data
     * @return $this
     */
    public function insert(string $table, array $data)
    {
        $keys   = array_keys($data);
        $fields = array_map(function ($key) {
            return ":{$key}";
        }, $keys);
        $sql    = "INSERT INTO `{$table}` (`" . implode('`, `', $keys) . "`) VALUES (" . implode(', ', $fields) . ")";
        $this->createCommand($sql);
        $this->bindParams($data);
        return $this;
    }

    /**
     * 批量插入
     * @param string $table
     * @param array $data
     * @return $this
     */
    public function batchInsert(string $table, array $data)
    {
        $keys   = array_keys($data[0]);
        $sql    = "INSERT INTO `{$table}` (`" . implode('`, `', $keys) . "`) VALUES ";
        $values = [];
        $subSql = [];
        foreach ($data as $item) {
            $tmp = [];
            foreach ($item as $key => $value) {
                // 原始方法
                if ($value instanceof Expression) {
                    $tmp[] = $value->getValue();
                    continue;
                }
                $values[] = $value;
                $tmp[]    = '?';
            }
            $subSql[] = "(" . implode(', ', $tmp) . ")";
        }
        $sql .= implode(', ', $subSql);
        $this->createCommand($sql);
        $this->bindValues($values);
        return $this;
    }

    /**
     * 更新
     * @param string $table
     * @param array $data
     * @param array $where
     * @return $this
     */
    public function update(string $table, array $data, array $where)
    {
        list($dataSql, $dataParams) = BuildHelper::buildData($data);
        list($whereSql, $whereParams) = BuildHelper::buildWhere($where);
        $this->createCommand([
            ["UPDATE `{$table}`"],
            ["SET {$dataSql}", 'params' => $dataParams],
            ["WHERE {$whereSql}", 'params' => $whereParams],
        ]);
        return $this;
    }

    /**
     * 删除
     * @param string $table
     * @param array $where
     * @return $this
     */
    public function delete(string $table, array $where)
    {
        list($sql, $params) = BuildHelper::buildWhere($where);
        $this->createCommand([
            ["DELETE FROM `{$table}`"],
            ["WHERE {$sql}", 'params' => $params],
        ]);
        return $this;
    }

    /**
     * 自动事务
     * @param $closure
     * @throws \Throwable
     */
    public function transaction($closure)
    {
        $this->beginTransaction();
        try {
            $closure();
            // 提交事务
            $this->commit();
        } catch (\Throwable $e) {
            // 回滚事务
            $this->rollBack();
            throw $e;
        }
    }

    /**
     * 开始事务
     * @return bool
     */
    public function beginTransaction()
    {
        // 自动连接
        $this->autoConnect();
        // 开始事务
        return $this->_pdo->beginTransaction();
    }

    /**
     * 提交事务
     * @return bool
     */
    public function commit()
    {
        return $this->_pdo->commit();
    }

    /**
     * 回滚事务
     * @return bool
     */
    public function rollback()
    {
        return $this->_pdo->rollBack();
    }

    /**
     * 启动查询生成器
     * @param string $table
     * @return QueryBuilder
     */
    public function table(string $table)
    {
        return QueryBuilder::new($this)->table($table);
    }

}
